### ISSUE TITLE
Add any Python Script

### ISSUE THREAD

**Issue by cryp73r** [priyanshusingh0610/python-proj#3]
**Which type of files are not allowed?**

1. Simple programs like printing 'Hello World' not allowed.
2. Should do something extraordinary.
3. Must be unique.
4. Assignment not necessary. Anyone can submit.
5. Should have proper description while creating request as well as same inside program as comment.

_Note: Please before making any pull request, check other pull request also. It must be unique._

**Comment by himik-nainwal** [comment]
I want to do a python program using kiwi to create a ping pong game .
Please assign

**Comment by rajeeviiit** [comment]
Hey @priyanshusingh0610 , I am interested in doing it...could you please assign it to me?

**Comment by Hinal-Srivastava** [comment]
@rajeeviiit @Himith as @priyanshusingh0610 has said, an assignment is not necessary.  You can contribute as long as your projects are not basics and should be unique

**Comment by himik-nainwal** [comment]
> @rajeeviiit @Himith as @priyanshusingh0610 has said, an assignment is not necessary. You can contribute as long as your projects are not basics and should be unique

Got that

**Comment by rajeeviiit** [comment]
Ok got it.
